server:
  port: 18083
spring:
  application:
    name: consumer-demo
  datasource:
    url: jdbc:mysql://150.158.165.32:3306/tsf_consumer?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: tsf_consumer
    password: tsf_consumer
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 150.158.165.32
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml