server:
  port: 18081
spring:
  application:
    name: provider-demo
  datasource:
    url: jdbc:mysql://150.158.165.32:3306/tsf?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: tsf
    password: tsf
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 150.158.165.32
    port: 6379
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml